// Curated non-standard authoritative WHOIS servers by TLD
export const WHOIS_TLD_EXCEPTIONS = {
  // gTLDs
  com: "whois.verisign-grs.com",
  net: "whois.verisign-grs.com",
  org: "whois.pir.org",
  info: "whois.afilias.net",
  biz: "whois.nic.biz",
  edu: "whois.educause.edu",
  gov: "whois.dotgov.gov",

  // ccTLDs and others
  de: "whois.denic.de",
  jp: "whois.jprs.jp",
  fr: "whois.nic.fr",
  it: "whois.nic.it",
  pl: "whois.dns.pl",
  nl: "whois.domain-registry.nl",
  be: "whois.dns.be",
  se: "whois.iis.se",
  no: "whois.norid.no",
  fi: "whois.fi",
  cz: "whois.nic.cz",
  es: "whois.nic.es",
  br: "whois.registro.br",
  ca: "whois.cira.ca",
  dk: "whois.dk-hostmaster.dk",
  hk: "whois.hkirc.hk",
  sg: "whois.sgnic.sg",
  in: "whois.registry.in",
  nz: "whois.srs.net.nz",
  ch: "whois.nic.ch",
  li: "whois.nic.li",
  io: "whois.nic.io",
  ai: "whois.nic.ai",
  ru: "whois.tcinet.ru",
  su: "whois.tcinet.ru",
  "xn--p1ai": "whois.tcinet.ru", // .рф

  // CentralNic-operated second-level zones (treat as exceptions here for simplicity)
  "uk.com": "whois.centralnic.com",
  "uk.net": "whois.centralnic.com",
  "gb.com": "whois.centralnic.com",
  "gb.net": "whois.centralnic.com",
  "eu.com": "whois.centralnic.com",
  "us.com": "whois.centralnic.com",
  "se.com": "whois.centralnic.com",
  "de.com": "whois.centralnic.com",
  "br.com": "whois.centralnic.com",
  "ru.com": "whois.centralnic.com",
  "cn.com": "whois.centralnic.com",
  "sa.com": "whois.centralnic.com",
} as Record<string, string>;
